[project]
name = "ainews-test"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "feedparser>=6.0.12",
    "ipykernel>=7.1.0",
    "pymongo>=4.15.5",
    "requests>=2.32.5",
]
